### ISSUE TITLE
sanity checks for image net?

### ISSUE THREAD

**Issue by brando90** [google-research/meta-dataset#105]
I was running
```
ls $MDS_DATA_PATH/ILSVRC2012_img_train/
ls $MDS_DATA_PATH/ILSVRC2012_img_train/ | grep -c .tar
# 5620
ls $MDS_DATA_PATH/ILSVRC2012_img_train/ -1 | grep -v "\.tar$" | wc -l
# 5622
```
and got those numbers in the comment. Are those the expect number of files for imagenet? Seems rather small?

**Comment by brando90** [comment]
is this a correct translation of your natural language instructions?
```
# - 1. Download ilsvrc2012_img_train.tar, from the ILSVRC2012 website
# todo: https://gist.github.com/bonlime/4e0d236cf98cd5b15d977dfa03a63643
# todo: https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md#ilsvrc_2012
# wget TODO -O $MDS_DATA_PATH/ilsvrc_2012
# for imagenet url: https://image-net.org/download-images.php
wget https://image-net.org/data/winter21_whole.tar.gz -O ~/data/winter21_whole.tar.gz
# there should be .gz file
ls ~/data/

# - 2. Extract it into ILSVRC2012_img_train/, which should contain 1000 files, named n????????.tar (expected time: ~30 minutes) ref: https://superuser.com/questions/348205/how-do-i-unzip-a-tar-gz-archive-to-a-specific-destination
mkdir -p ~/data/winter21_whole
tar xf ~/data/winter21_whole.tar.gz -C ~/data/
# (expected time: ~30 minutes)
ls ~/data/winter21_whole
# move the train part (mv src dest)
mkdir -p $MDS_DATA_PATH/ILSVRC2012_img_train/
mv ~/data/winter21_whole/* $MDS_DATA_PATH/ILSVRC2012_img_train/

# check files are there
ls $MDS_DATA_PATH/ILSVRC2012_img_train/
ls $MDS_DATA_PATH/ILSVRC2012_img_train/ | grep -c .tar

# - 3. Extract each of ILSVRC2012_img_train/n????????.tar in its own directory (expected time: ~30 minutes), for instance:
for FILE in $MDS_DATA_PATH/ILSVRC2012_img_train/*.tar;
do
  #echo $FILE
  mkdir ${FILE/.tar/};
  cd ${FILE/.tar/};
  tar xvf ../$FILE;
  cd ..;
done
# (expected time: ~30 minutes)
ls $MDS_DATA_PATH/ILSVRC2012_img_train/
ls $MDS_DATA_PATH/ILSVRC2012_img_train/ | grep -c .tar
# 5620
ls $MDS_DATA_PATH/ILSVRC2012_img_train/ -1 | grep -v "\.tar$" | wc -l
# 5622

# - 4. Download the following two files into ILSVRC2012_img_train/
wget http://www.image-net.org/data/wordnet.is_a.txt -O $MDS_DATA_PATH/ILSVRC2012_img_train/wordnet.is_a.txt
wget http://www.image-net.org/data/words.txt -O $MDS_DATA_PATH/ILSVRC2012_img_train/words.txt
#
cat $MDS_DATA_PATH/ILSVRC2012_img_train/wordnet.is_a.txt
cat $MDS_DATA_PATH/ILSVRC2012_img_train/words.txt
ls $MDS_DATA_PATH/ILSVRC2012_img_train/ | grep -c "*"

# - 5. Launch the conversion script (Use --dataset=ilsvrc_2012_v2 for the training only MetaDataset-v2 version):
python -m meta_dataset.dataset_conversion.convert_datasets_to_records \
  --dataset=ilsvrc_2012 \
  --ilsvrc_2012_data_root=$MDS_DATA_PATH/ILSVRC2012_img_train \
  --splits_root=$SPLITS \
  --records_root=$RECORDS

# -6. Expect the conversion to take 4 to 12 hours, depending on the filesystem's latency and bandwidth.

# -7.Find the following outputs in $RECORDS/ilsvrc_2012/:
#1000 tfrecords files named [0-999].tfrecords
ls $RECORDS/ilsvrc_2012/ | grep -c .tfrecords
#dataset_spec.json (see note 1)
ls $RECORDS/ilsvrc_2012/dataset_spec.json
#num_leaf_images.json
ls $RECORDS/ilsvrc_2012/num_leaf_images.json
```

**Comment by brando90** [comment]
current error I have:
```
leafs: mandibular notch and angelfish. LCA: entity
I0106 10:08:41.794109 139919327179392 imagenet_stats.py:158] Finegrainedness analysis of test graph using longest paths in finding the lowest common ancestor.
I0106 10:08:42.020792 139919327179392 imagenet_stats.py:191] Stats on the height of the Lowest Common Ancestor of random leaf pairs of the test graph: mean: 3.8368, median: 4.0, max: 8, min: 1
I0106 10:08:42.020935 139919327179392 imagenet_stats.py:202] Proportion of example leaf pairs (out of num_leaf_pairs random pairs) for each height of the LCA of the leaves: {3: 0.3299, 2: 0.081, 4: 0.3554, 6: 0.0522, 5: 0.1395, 7: 0.0244, 8: 0.0092, 1: 0.0084}
I0106 10:08:42.020989 139919327179392 imagenet_stats.py:208] Proportion of example leaf pairs per height whose LCA is the root: {3: 0.8790542588663232, 2: 0.6061728395061728, 4: 0.9425998874507597, 6: 0.9252873563218391, 5: 0.9369175627240144, 7: 0.8811475409836066, 8: 1.0, 1: 0.16666666666666666}
I0106 10:08:42.021031 139919327179392 imagenet_stats.py:212] Examples with different fine-grainedness:

I0106 10:08:42.021075 139919327179392 imagenet_stats.py:218] Examples with height 3:
leafs: press and wiper motor. LCA: device
I0106 10:08:42.021108 139919327179392 imagenet_stats.py:218] Examples with height 3:
leafs: jigsaw, scroll saw, fretsaw and spinet. LCA: device
I0106 10:08:42.021146 139919327179392 imagenet_stats.py:218] Examples with height 2:
leafs: sonograph and convector. LCA: device
I0106 10:08:42.021184 139919327179392 imagenet_stats.py:218] Examples with height 2:
leafs: band and outrigger. LCA: device
I0106 10:08:42.021220 139919327179392 imagenet_stats.py:218] Examples with height 4:
leafs: tenpenny nail and three-dimensional radar, 3d radar. LCA: device
I0106 10:08:42.021264 139919327179392 imagenet_stats.py:218] Examples with height 4:
leafs: body plethysmograph and peg. LCA: device
I0106 10:08:42.021298 139919327179392 imagenet_stats.py:218] Examples with height 6:
leafs: pinion and digital-analog converter, digital-to-analog converter. LCA: device
I0106 10:08:42.021341 139919327179392 imagenet_stats.py:218] Examples with height 6:
leafs: harvester, reaper and hydroelectric turbine. LCA: machine
I0106 10:08:42.021379 139919327179392 imagenet_stats.py:218] Examples with height 5:
leafs: alarm clock, alarm and coelostat. LCA: device
I0106 10:08:42.021414 139919327179392 imagenet_stats.py:218] Examples with height 5:
leafs: drive line, drive line system and transit instrument. LCA: device
I0106 10:08:42.021447 139919327179392 imagenet_stats.py:218] Examples with height 7:
leafs: steam turbine and bicycle wheel. LCA: device
I0106 10:08:42.021480 139919327179392 imagenet_stats.py:218] Examples with height 7:
leafs: Reaumur thermometer and steam turbine. LCA: device
I0106 10:08:42.021514 139919327179392 imagenet_stats.py:218] Examples with height 8:
leafs: flugelhorn, fluegelhorn and Cassegrainian telescope, Gregorian telescope. LCA: device
I0106 10:08:42.021547 139919327179392 imagenet_stats.py:218] Examples with height 8:
leafs: bicycle wheel and Newtonian telescope, Newtonian reflector. LCA: device
I0106 10:08:42.021582 139919327179392 imagenet_stats.py:218] Examples with height 1:
leafs: thermopile and Beckman thermometer. LCA: thermometer
I0106 10:08:42.021614 139919327179392 imagenet_stats.py:218] Examples with height 1:
leafs: bicycle wheel and rowel. LCA: wheel
I0106 10:08:42.035706 139919327179392 convert_datasets_to_records.py:151] Creating ImageNet ILSVRC-2012 specification and records in directory /lfs/ampere4/0/brando9/data/mds/records/ilsvrc_2012...
Traceback (most recent call last):
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 157, in <module>
    tf.app.run(main)
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 153, in main
    converter.convert_dataset()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 610, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1574, in create_dataset_specification_and_records
    assert set_of_directories == set(all_synset_ids), (
AssertionError: self.data_root should contain a directory whose name is the WordNet id of each synset that is a leaf of any split's subgraph.
```

anyone has a suggestion on how to fix it?
