### ISSUE TITLE
JSONDecoder Error when converting vgg_flower

### ISSUE THREAD

**Issue by SongJaeYun** [google-research/meta-dataset#19]
When I converting vgg_flower, there is a issue.
Could you give me a suggestion to solve this problem?

I put it on home directory
python3 -m meta_dataset.dataset_conversion.convert_datasets_to_records \
  --dataset=aircraft \
  --aircraft_data_root=/hdd/FSMTL/fgvc-aircraft-2013b \
  --splits_root=/hdd/meta_dataset/splits \
  --records_root=/hdd/meta_dataset/records.

Then, I got
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/server11/song/models/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 138, in <module>
    tf.app.run(main)
  File "/home/server11/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/server11/song/models/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 134, in main
    converter.convert_dataset()
  File "/home/server11/song/models/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 546, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/home/server11/song/models/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 953, in create_dataset_specification_and_records
    splits = self.get_splits()
  File "/home/server11/song/models/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 629, in get_splits
    splits = self.read_splits()
  File "/home/server11/song/models/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 588, in read_splits
    splits = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 5 (char 19)

**Comment by lamblin** [comment]
I just reproduced that issue with Python 3.
1. First conversion attempts to serialize an int64, which fails (was working on Python2), and leaves a partial (incorrect) file.
2. Second conversion sees an existing json file, and fails loading it.

When 1. is fixed, you can manually remove the .json file and try again.

**Comment by SongJaeYun** [comment]
Thank you! I fixed it.
