### ISSUE TITLE
Fungi script throws "no train.json" error while clearly there is a train.json file in the reference folder

### ISSUE THREAD

**Issue by peymanbateni** [google-research/meta-dataset#23]
Here's the error log:

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 152, in <module>
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 148, in main
    converter.convert_dataset()
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 548, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1571, in create_dataset_specification_and_records
    splits = self.get_splits()
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 644, in get_splits
    splits = self.create_splits()
  File "/home/ubuntu/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1541, in create_splits
    original_train = json.load(f)
  File "/home/ubuntu/anaconda3/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: $../DATA/fungi/train.json; No such file or directory

~/meta-dataset$ cd ../DATA/fungi/

~/DATA/fungi$ ls
images  train.json  val.json

~/DATA/fungi$`

**Comment by peymanbateni** [comment]
Sorry, there was a typo I had missed. Apologies!!
