### ISSUE TITLE
I have a problem about using MSCOCO Dataset

### ISSUE THREAD

**Issue by gongyu0217** [google-research/meta-dataset#53]
Windows10, tensorflow 1.12,coco dataset,val2017,instanceval2007
I have a peoblem when running convert_datasets_to_records.py.

`Traceback (most recent call last):
  File "E:\PyCharm\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\pydevconsole.py", line 305, in do_exit
    import java.lang.System
  File "E:\PyCharm\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named 'java'`

**Comment by gongyu0217** [comment]
Solved！！！tensorflow 1.14，python 3.7. But I'don't know the reason.
