### ISSUE TITLE
FLUTE Best .gin has missing values?

### ISSUE THREAD

**Issue by gstoica27** [google-research/meta-dataset#80]
Hi,

When I try to run the FLUTE model using the "best .gin" configuration,

```
python -m meta_dataset.train_flute --train_checkpoint_dir=<CKPT_DIR>/meta_dataset --summary_dir=<ROOT_DIR>/meta_dataset/ --records_root_dir=<DATA_DIR>/meta_dataset/records --alsologtostderr --gin_config=meta_dataset/learn/gin/best/flute.gin --gin_bindings="Trainer_flute.experiment_name='flute'"
```

I keep receiving errors: E.g.,

```
Use `tf.data.Dataset.choose_from_datasets(...)` instead. Note that, unlike the experimental endpoint, the non-experimental endpoint sets `stop_on_empty_dataset=True` by default. You should set this argument explicitly in case you would like to match the behavior of the experimental endpoint.
Traceback (most recent call last):
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nethome/gstoica3/research/meta-dataset/meta_dataset/train_flute.py", line 186, in <module>
    app.run(program)
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/nethome/gstoica3/research/meta-dataset/meta_dataset/train_flute.py", line 140, in main
    num_gpus=FLAGS.num_gpus)
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/nethome/gstoica3/research/meta-dataset/meta_dataset/trainer_flute.py", line 516, in __init__
    tied_learner=tied_learner)
  File "/nethome/gstoica3/research/meta-dataset/meta_dataset/trainer_flute.py", line 852, in create_learner
    input_shape=self.image_shape,
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/nethome/gstoica3/anaconda3/envs/md_env/lib/python3.7/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
TypeError: __init__() missing 1 required positional argument: 'num_sets'
  No values supplied by Gin or caller for arguments: ['num_sets']
  Gin had values bound for: []
  Caller supplied values for: ['input_shape', 'is_training', 'logit_dim', 'self']
  In call to configurable 'DatasetConditionalBaselineLearner' (<class 'meta_dataset.learners.baseline_learners.DatasetConditionalBaselineLearner'>)
  In call to configurable 'Trainer_flute' (<class 'meta_dataset.trainer_flute.Trainer'>)
srun: error: clank: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=199056.0
```

How should we be using the best configuration? For instance, would we replace corresponding values in the default FLUTE gin with ones in the best gin, while leaving all other args the same?

Thanks very much!

**Comment by eleniTriantafillou** [comment]
Hi there!

It looks like your command runs *training* of FLUTE, but uses the gin config that is intended for *evaluation* of FLUTE, which doesn't have all of the required values set.

The commands for running either training or evaluation can be found at the top of the `train_flute.py` file, starting in [this](https://github.com/google-research/meta-dataset/blob/c67dd2bb66fb2a4ce7e4e9906878e13d9b851eb5/meta_dataset/train_flute.py#L20) line.
Notice that the `gin_config` is different between the training and test commands there.

I hope this helps. Please let us know if there are additional issues!

**Comment by vdumoulin** [comment]
We will close the issue for now, but feel free to reopen if you have any additional questions.
